### ISSUE TITLE
Plugin does not work on PhoneGap Android 7.1.2

### ISSUE THREAD

**Issue by rcha103** [tjwoon/csIPay88#15]
Hi, I am having issues when installing your plugin on my PhoneGap project. Due to the requirements from [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements), I need to use Cordova Android version 7.1.2. However, I am getting the below errors:

```BUILD FAILED in 14s
31 actionable tasks: 31 executed
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/app/src/main/java/org/cloudsky/cordovaPlugins/IPay88.java:14: error: package com.ipay does not exist
import com.ipay.Ipay;
               ^
/app/src/main/java/org/cloudsky/cordovaPlugins/IPay88.java:15: error: package com.ipay does not exist
import com.ipay.IpayPayment;
               ^
/app/src/main/java/org/cloudsky/cordovaPlugins/IPay88.java:16: error: package com.ipay does not exist
import com.ipay.IpayResultDelegate;
               ^
/app/src/main/java/org/cloudsky/cordovaPlugins/IPay88.java:40: error: cannot find symbol
    static public class ResultDelegate implements IpayResultDelegate, Serializable {
                                                  ^
  symbol:   class IpayResultDelegate
  location: class IPay88
/app/src/main/java/org/cloudsky/cordovaPlugins/IPay88.java:234: error: cannot find symbol
        IpayPayment payment = new IpayPayment();
        ^
  symbol:   class IpayPayment
  location: class IPay88
/app/src/main/java/org/cloudsky/cordovaPlugins/IPay88.java:234: error: cannot find symbol
        IpayPayment payment = new IpayPayment();
                                  ^
  symbol:   class IpayPayment
  location: class IPay88
/app/src/main/java/org/cloudsky/cordovaPlugins/IPay88.java:254: error: cannot find symbol
        Intent checkoutIntent = Ipay.getInstance().checkout(
                                ^
  symbol:   variable Ipay
  location: class IPay88
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileArmv7DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

Build works with PhoneGap iOS 4.5.5. Any suggestions?
